### PR TITLE
Fix for RT#98034 where Mojolicious calls format()

### PR DESCRIPTION
**Pull request by brad-mac**
The format() method is needed although it doesn't really do anything much; in order to not break anything it just joins the passed-in lines with newlines.

### CODE REVIEW

**Comment by stuartskelton** [comment]
This would be really great to have.

**Comment by brad-mac** [comment]
*bump*

**Comment by garu** [comment]
Hi everyone! Sorry for the long wait, and thanks for the PR. Although I have merged it, it looks like this is a backport from one of my own commits fixing this issue in the 0.10 release of this dist, **back in August, 2014**. It even includes [my own code commented out from it](https://github.com/garu/MojoX-Log-Log4perl/pull/4/files#diff-2a39a2a11e36c6a068880291c8194ed6R20), which is only on MetaCPAN and not pushed onto this repo (yet).

@brad-mac could you please tell me why this is so? Did I overlook something? Unless there's some logical explanation, I'm going to have to make a merge and push my own code for the issue (which was not pushed onto the repo but you found and used from metacpan).

Thanks!

**Comment by garu** [comment]
@brad-mac a-ha! If I had bothered to actually **read** [issue #98034](https://rt.cpan.org/Public/Bug/Display.html?id=98034), I would know exactly what happened :)

I'll keep the warning off of format, though I really wish there was a better way to do this. I mean, our bogus `format()` being called so often likely makes log4perl overkill in this scenario 😑 

Anyway, thanks again for the PR! I'll push the current (merged) code and send a new version to metacpan!

Cheers,

garu

**Comment by garu** [comment]
Done! MojoX::Log::Log4perl should hit your local CPAN mirror anytime soon. The master branch of this repository is also updated and sync'd, so if you have any other feature requests or issues and want to send some more PRs, just let me know!

Thanks again!

Cheers,

garu

**Comment by brad-mac** [comment]
Thanks Garu - much appreciated :-) It’s very handy being able to use Log::Log4perl to fine-tune the logging for Mojo like this.

Cheers

Brad

**Pull request merged**
